# Generated by Django 2.1.7 on 2019-02-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('last', models.DecimalField(decimal_places=4, max_digits=18)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=18)),
                ('sell', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=18)),
                ('sell', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now=True)),
                ('bitcoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bitcoin')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('points', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variation', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stocks'),
        ),
    ]
