# Generated by Django 2.1.7 on 2019-02-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='buy',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='format',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='last',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='sell',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='variation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='variation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='points',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='variation',
            field=models.FloatField(null=True),
        ),
    ]
